export const authConstants ={
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}


export const categoryConstants ={
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
    ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE: 'ADD_NEW_CATEGORY_FAILURE',

}

export const productConstants ={
    GET_PRODUCTS_BY_SLUG: 'GET_PRODUCTS_BY_SLUG',
    GET_PRODUCT_PAGE_REQUEST: 'GET_PRODUCT_PAGE_REQUEST',
    GET_PRODUCT_PAGE_SUCCESS: 'GET_PRODUCT_PAGE_SUCCESS',
    GET_PRODUCT_PAGE_FAILURE: 'GET_PRODUCT_PAGE_FAILURE',

    GET_PRODUCT_DETAILS_BY_EID_REQUEST: 'GET_PRODUCT_DETAILS_BY_EID_REQUEST',
    GET_PRODUCT_DETAILS_BY_EID_SUCCESS: 'GET_PRODUCT_DETAILS_BY_EID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_EID_FAILURE: 'GET_PRODUCT_DETAILS_BY_EID_FAILURE',


}

export const cartConstants = {
    ADD_TO_CART__REQUEST: 'ADD_TO_CART__REQUEST',
    ADD_TO_CART__SUCCESS: 'ADD_TO_CART__SUCCESS',
    ADD_TO_CART__FAILURE: 'ADD_TO_CART__FAILURE',
    RESET_CART: 'RESET_CART',
}



export const userConstants = {
    GET_USER_ADDRESS__REQUEST: 'GET_USER_ADDRESS__REQUEST',
    GET_USER_ADDRESS__SUCCESS: 'GET_USER_ADDRESS__SUCCESS',
    GET_USER_ADDRESS__FAILURE: 'GET_USER_ADDRESS__FAILURE',

    ADD_USER_ADDRESS__REQUEST: 'ADD_USER_ADDRESS__REQUEST',
    ADD_USER_ADDRESS__SUCCESS: 'ADD_USER_ADDRESS__SUCCESS',
    ADD_USER_ADDRESS__FAILURE: 'POST_USER_ADDRESS__FAILURE',
}
